server:
  filter_type: "postfix"
  listen_address: "0.0.0.0:10025"
  block_spam: false
  headers:
    spam: "X-Spam-Status"
    score: "X-Spam-Score"
    reason: "X-Spam-Reason"
  postfix:
    enabled: true
    address: "127.0.0.1"
    port: 10026

llm:
  provider: "bedrock"  # Options: "bedrock", "gemini", "openai"

bedrock:
  region: "us-east-1"
  model_id: "anthropic.claude-v2"
  max_tokens: 1000
  temperature: 0.1
  top_p: 0.9
  max_body_size: 4096

gemini:
  api_key: ""
  model_name: "gemini-pro"
  max_tokens: 1000
  temperature: 0.1
  top_p: 0.9
  max_body_size: 4096

openai:
  api_key: ""
  model_name: "gpt-4"
  max_tokens: 1000
  temperature: 0.1
  top_p: 0.9
  max_body_size: 4096

spam:
  threshold: 0.7
  whitelisted_domains:
    - "example.com"
    - "trusted-company.org"

cache:
  type: "memory"  # Options: "memory", "sqlite", "mysql"
  enabled: true
  ttl: "24h"
  cleanup_frequency: "1h"
  sqlite_path: "/data/spam_cache.db"
  mysql_dsn: "user:password@tcp(localhost:3306)/spam_filter"

logging:
  level: "info"
  format: "json"
